from typing import Sequence

class EntityListModel:
    def __init__(self, *args, name: str | None = ..., category: str | None = ..., ranked: bool = ..., entities: Sequence[str] | None = ...) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def entities(self) -> Sequence[str]: ...
    @property
    def is_ranked(self) -> bool: ...
