from maic import Maic as Maic
from unittest import TestCase

class TestMaic(TestCase):
    def test_make_output_folder_undefined_path(self) -> None: ...
    def test_make_output_folder_blank_path(self) -> None: ...
    def test_make_output_folder_dot_path(self) -> None: ...
    def test_make_output_folder_simple_path(self, mock_makedirs) -> None: ...
    def test_make_output_folder_simple_path_with_slash(self, mock_makedirs) -> None: ...
    def test_make_output_folder_path_with_multi_slashes(self, mock_makedirs) -> None: ...
    def test_make_output_folder_exists_no_timestamp(self, mock_makedirs, mock_logger) -> None: ...
    def test_make_output_folder_exists_with_timestamp_fails(self, mock_makedirs) -> None: ...
